### ISSUE TITLE
(De-)hydrating null values

### ISSUE THREAD

**Issue by Zwartpet** [kleijnweb/php-api-hydrator#4]
This is more a question than an issue i gues.
Is it by design that undefined nodes throw an error when hydrating/dehydrating?

Ex:
``` javascript
{
  title: {
    type: string // returns error with value NULL when hydrating
  }, 
  contract: {
    type: object //returns error with value NULL when hydrating and dehydrating
  }
}
```

**Comment by johnknl** [comment]
It makes sense that it would fail when the input is not compatible with the schema. Passing `key: NULL` is not the same as omitting the key and its value and would only be valid if the expected type was actually "null" (`Schema::TYPE_NULL`).

The input is expected to be valid with the schema, so at least that part is "by design". Might need a better exception though. What are you encountering?

**Comment by Zwartpet** [comment]
The problem with the input having NULL values is because of the hydrator setting those when dehydrating an object. I just send the same object back in an UPDATE

**Comment by johnknl** [comment]
Ah. Then probably the dehydrating behavior for NULL values should change, ensuring the output is valid with the schema. 

We would have to check the schema: if a value is optional, omit the key, if not, use a default. For composites, this gets a little muddy, consider:

`(object)[ 'foo' => null ]`

With a schema:

```
foo:
  type: object
  required: ['id', 'blah']
  properties:
    id: { type: int }
    bar: { type: string }
    blah: { type: string }
```

The dehydrated object would then become:

```
{ foo: { id: 0, blah: '' }}
```
This is right way to go about it I think but a little work and something that definitely has consequences for clients. Especially when passing out-of-context (partial) schema's where the root 'required' declaration is lost.

**Comment by Zwartpet** [comment]
So, is it done yet :P
A lot of holidays coming up, maybe I’ll make an attempt at fixing when I’m fed up with the social plesantries

**Comment by Zwartpet** [comment]
Not sure though if the Hydrator should validate the required properties against the schema.
If the schema holds a default value it might be able to use this when the property is NULL, but adding random defaults for missing properties does not sound like a valid way to go.

When creating an object it should already validate against the schema (at least the required properties), so dehydrating objects with missing required properties will probably never occur.

**Comment by johnknl** [comment]
Hmm. On second thought, I agree that forcing the output to be valid is not the way to go. You may want to validate the object after dehydration which sounds like a common use case.

It still needs better NULL value handling though. So when a NULL value is encountered (and type is not null) it should filter the key. 

Applying the defaults before and after hydration and dehydration respectively arguably does not have much to do directly with the function of this package, but might be pragmatic. It prevents clients having to do the same recursive processing. Alternatively I could implement a Visitor-type mechanism but that sounds like overkill for a single type of processing.

**Comment by kiddigital** [comment]
I also agree that the dehydration should not do output validation. It should be able to gracefully handle objects that might not be according to spec.

Even type mismatches between the dehydrated object and the schema can be considered out-of-scope for the dehydration. There is no need for the schema as the object is fully typed.

But as the dehydration knows the schema, it could do the following very easily:
* strip/filter out NULL values indeed (when type is not null). Very useful to dehydrate an object that actually contains a superset of properties/object in relation to the schema.
* add properties/objects that are not in the initial object but defined in the schema and with a default value (when no default value is available, they should be skipped). Very useful to add more static information to the result instead of coding it into the object before dehydration.

So for your example:
`(object)[ 'foo' => null ]`
I would expect the following result
`{}`

And when (on purpose omitting 'blah'):
`(object)['foo' => (object)[ 'id' => (int)42]]`
With schema:
```
foo:
  type: object
  required: ['id', 'blah']
  properties:
    id: { type: int }
    bar: { type: string, default: 'drinks' }
    blah: { type: string }
```
I would expect
`
{ foo: { id: 42, bar: 'drinks' }}
`

**Comment by johnknl** [comment]
@kiddigital I think we're all on mostly on the same page here. 

A thing to consider is applying the defaults when hydrating instead of dehydrating. This seems more useful to me than doing it when dehydrating (since some application logic might be dependent on the default value), and gives a more accurate representation of the output when dehydrating. If an object property became NULL between hydration and dehydration, it makes sense that this would not pass validation if the property was marked as required, even if a default was defined.

I minor note on this quote:

> strip/filter out NULL values indeed (when type is not null). Very useful to dehydrate an object that actually contains a superset of properties/object in relation to the schema.

The schema is not the base for the output, the properties in the object are. This is desired behavior so that validation can happen on the full data set, taking into account `additionalProperties`. So if an object contains a superset of the properties in the schema, so will the output. If we filter all properties with NULL values unless type null (which we should) there is the edge case where the "extra" property was actually intended to be NULL, but the hydrator cannot know that without schema. But yeah, that is definitely an edge case with limited practical applicability.

**Comment by johnknl** [comment]
NULL filtering for object properties is now in v1.0.0-alpha3. Applying defaults when hydrating is going to have to wait a little.

**Comment by johnknl** [comment]
alpha-4 now has support for default values (when hydrating). Let me know if you want anything else, otherwise I'm going to close this.

**Comment by Zwartpet** [comment]
Implemented and tested in a project, seems to work. Closing issue
